package ch.bfh.btx8081.w2014.red.health;

import javax.servlet.annotation.WebServlet;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.Theme;
import com.vaadin.annotations.VaadinServletConfiguration;
import com.vaadin.server.ThemeResource;
import com.vaadin.server.VaadinRequest;
import com.vaadin.server.VaadinServlet;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.UI;

@Theme("mytheme")
@SuppressWarnings("serial")

public class VaadinUI extends UI {
	

    @WebServlet(value = "/*", asyncSupported = true)
    @VaadinServletConfiguration(productionMode = false, ui = VaadinUI.class, widgetset = "ch.bfh.btx8081.w2014.red.health.AppWidgetSet")
    public static class Servlet extends VaadinServlet {
    }
	
	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_title;
	@AutoGenerated
	private TextField textField_details;
	@AutoGenerated
	private Label label_lastname;
	@AutoGenerated
	private Label label_firstname;
	@AutoGenerated
	private Label label_status;
	@AutoGenerated
	private Button button_details;
	@AutoGenerated
	private Embedded embedded_picture;
	
	
	
	
	
	
	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public VaadinUI() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	private void setCompositionRoot(AbsoluteLayout mainLayout2) {
		// TODO Auto-generated method stub
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// embedded_picture
		embedded_picture = new Embedded();
		embedded_picture.setImmediate(false);
		embedded_picture.setWidth("100.0%");
		embedded_picture.setHeight("200px");
		embedded_picture.setSource(new ThemeResource(
				"img/component/embedded_icon.png"));
		embedded_picture.setType(1);
		embedded_picture.setMimeType("image/png");
		mainLayout.addComponent(embedded_picture,
				"top:100.0px;right:415.0px;left:61.0px;");
		
		// button_details
		button_details = new Button();
		button_details.setCaption("Details");
		button_details.setImmediate(true);
		button_details.setWidth("100.0%");
		button_details.setHeight("-1px");
		mainLayout.addComponent(button_details,
				"top:280.0px;right:290.0px;left:340.0px;");
		
		// label_status
		label_status = new Label();
		label_status.setImmediate(false);
		label_status.setWidth("-1px");
		label_status.setHeight("-1px");
		label_status.setValue("Status :");
		mainLayout.addComponent(label_status, "top:182.0px;left:340.0px;");
		
		// label_firstname
		label_firstname = new Label();
		label_firstname.setImmediate(false);
		label_firstname.setWidth("-1px");
		label_firstname.setHeight("-1px");
		label_firstname.setValue("Firstname:");
		mainLayout.addComponent(label_firstname, "top:102.0px;left:340.0px;");
		
		// label_lastname
		label_lastname = new Label();
		label_lastname.setImmediate(false);
		label_lastname.setWidth("-1px");
		label_lastname.setHeight("-1px");
		label_lastname.setValue("Lastname:");
		mainLayout.addComponent(label_lastname, "top:142.0px;left:340.0px;");
		
		// textField_details
		textField_details = new TextField();
		textField_details.setCaption("Details");
		textField_details.setImmediate(false);
		textField_details.setWidth("600px");
		textField_details.setHeight("160px");
		mainLayout.addComponent(textField_details, "top:360.0px;left:60.0px;");
		
		// label_title
		label_title = new Label();
		label_title.setImmediate(false);
		label_title.setWidth("-1px");
		label_title.setHeight("-1px");
		label_title.setValue("Client View");
		mainLayout.addComponent(label_title, "top:40.0px;left:61.0px;");
		
		return mainLayout;
	}

	@Override
	protected void init(VaadinRequest request) {
		// TODO Auto-generated method stub
		
	}

}
